# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e6a0b5534df89abce82ec1ddc7ef5b219ae3a05b0e603fedfdc8509cb6584d83c82e720f244d204f4ccef135d8fa815515007e6aa5b03548359b53b958529db

test:
  secret_key_base: 585e4dbc9cf464ddf6e76596aa6a96ea1911293c3e7cffd526164a8f6b64b127ca1aff0a44b2058706c905ec4b08a11c6f945ffd8b80abaf5462f98bc8c217e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
